# =============================================================================
# zybo_z710_mlp.xdc — Timing and I/O constraints
# Target: Digilent Zybo Z7-10  (XC7Z010-1CLG400C)
#
# The MLP accelerator runs entirely on FCLK_CLK0 generated by the Zynq PS.
# There is no external user clock to constrain.
# =============================================================================

# -----------------------------------------------------------------------------
# Primary clock — PS fabric clock FCLK_CLK0 at 100 MHz
# In the block design this clock is created by the Zynq PS IP.
# Vivado usually infers it automatically; this constraint makes it explicit
# so timing closure targets 100 MHz.
# -----------------------------------------------------------------------------
create_clock -period 10.000 -name clk_fpga_0 \
    [get_pins -hierarchical -filter {NAME =~ */PS7_i/FCLKCLK[0]}]

# -----------------------------------------------------------------------------
# Async reset false path
# FCLK_RESET0_N is synchronised by the Processor System Reset IP before
# reaching the AXI fabric.  No timing path crosses the raw reset.
# -----------------------------------------------------------------------------
set_false_path -from [get_pins -hierarchical -filter {NAME =~ */PS7_i/FCLKRESETN[0]}]

# -----------------------------------------------------------------------------
# Input/output delays — AXI and BRAM signals are all on-chip (PS ↔ PL),
# so no board-level I/O timing constraints are needed for the accelerator.
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Zybo Z7-10 on-board LED pin assignments (LD0–LD3)
# Uncomment and connect to your top-level ports if you want to use the LEDs,
# e.g. to display the 4-bit result or a busy indicator.
# -----------------------------------------------------------------------------
# set_property PACKAGE_PIN M14 [get_ports {led[0]}]
# set_property PACKAGE_PIN M15 [get_ports {led[1]}]
# set_property PACKAGE_PIN G14 [get_ports {led[2]}]
# set_property PACKAGE_PIN D18 [get_ports {led[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {led[*]}]