// mlp_params.vh — AUTO-GENERATED by train_and_export.py
// DO NOT EDIT: re-run train_and_export.py to regenerate.
//
// Inter-layer requantization right-shifts for mlp_engine.v
// act_int8 = clip(ReLU(acc_int32 >>> shift), 0, 127)
`define MLP_REQ_SHIFT_FC1  5'd11
`define MLP_REQ_SHIFT_FC2  5'd8
