// mlp_params.vh is auto-generated by train_and_export.py and defines:
//   `MLP_REQ_SHIFT_FC1  — right-shift for FC1 output requantization
//   `MLP_REQ_SHIFT_FC2  — right-shift for FC2 output requantization
// Re-run train_and_export.py after retraining; then re-synthesise in Vivado.
`include "mlp_params.vh"

// =============================================================================
// mlp_top.v
//
// Top-level wrapper for the 4-bank parallel MLP accelerator on Zybo Z7-10.
// Instantiates:
//   - axilite_ctrl  : AXI4-Lite slave (PS control/status interface)
//   - mlp_engine    : 4-neuron-parallel MAC inference engine
//
// Param BRAM Port B signals are split across 4 banks, each brought to
// top-level ports so the Vivado block diagram can wire them independently
// to the 4 BRAM primitives.  All 4 banks share the same address and enable;
// each returns its own 32-bit read data word.
//
// Busy signal: SR latch — set on start pulse, cleared on done pulse.
// =============================================================================
`timescale 1ns / 1ps

module mlp_top (
    // ── AXI4-Lite slave (connect to Zynq GP0 master) ─────────────────────────
    input  wire        s_axi_aclk,
    input  wire        s_axi_aresetn,

    input  wire [3:0]  s_axi_awaddr,
    input  wire        s_axi_awvalid,
    output wire        s_axi_awready,

    input  wire [31:0] s_axi_wdata,
    input  wire [3:0]  s_axi_wstrb,
    input  wire        s_axi_wvalid,
    output wire        s_axi_wready,

    output wire [1:0]  s_axi_bresp,
    output wire        s_axi_bvalid,
    input  wire        s_axi_bready,

    input  wire [3:0]  s_axi_araddr,
    input  wire        s_axi_arvalid,
    output wire        s_axi_arready,

    output wire [31:0] s_axi_rdata,
    output wire [1:0]  s_axi_rresp,
    output wire        s_axi_rvalid,
    input  wire        s_axi_rready,

    // ── Param BRAM — 4 banks, Port B (read-only) ─────────────────────────────
    // All 4 banks receive the same address and enable each cycle.
    // Each returns its own 32-bit word (weights/bias for one of the 4
    // parallel neurons being computed).
    output wire [13:0] param_bram_addr,
    output wire        param_bram_en,
    input  wire [31:0] param_bram0_rdata,
    input  wire [31:0] param_bram1_rdata,
    input  wire [31:0] param_bram2_rdata,
    input  wire [31:0] param_bram3_rdata,

    // ── Input BRAM — Port B (read-only) ──────────────────────────────────────
    output wire [9:0]  input_bram_addr,
    output wire        input_bram_en,
    input  wire [31:0] input_bram_rdata
);

// ── Internal wires ────────────────────────────────────────────────────────────
wire        start_w;
wire        done_w;
wire [3:0]  result_w;
reg         busy_r;

// ── Busy SR latch: set on start, clear on done ────────────────────────────────
always @(posedge s_axi_aclk or negedge s_axi_aresetn) begin
    if (!s_axi_aresetn)
        busy_r <= 1'b0;
    else if (start_w)
        busy_r <= 1'b1;
    else if (done_w)
        busy_r <= 1'b0;
end

// ── AXI4-Lite control/status block ───────────────────────────────────────────
axilite_ctrl u_ctrl (
    .s_axi_aclk     (s_axi_aclk),
    .s_axi_aresetn  (s_axi_aresetn),

    .s_axi_awaddr   (s_axi_awaddr),
    .s_axi_awvalid  (s_axi_awvalid),
    .s_axi_awready  (s_axi_awready),

    .s_axi_wdata    (s_axi_wdata),
    .s_axi_wstrb    (s_axi_wstrb),
    .s_axi_wvalid   (s_axi_wvalid),
    .s_axi_wready   (s_axi_wready),

    .s_axi_bresp    (s_axi_bresp),
    .s_axi_bvalid   (s_axi_bvalid),
    .s_axi_bready   (s_axi_bready),

    .s_axi_araddr   (s_axi_araddr),
    .s_axi_arvalid  (s_axi_arvalid),
    .s_axi_arready  (s_axi_arready),

    .s_axi_rdata    (s_axi_rdata),
    .s_axi_rresp    (s_axi_rresp),
    .s_axi_rvalid   (s_axi_rvalid),
    .s_axi_rready   (s_axi_rready),

    .start          (start_w),
    .busy           (busy_r),
    .done           (done_w),
    .result         (result_w)
);

// ── MLP inference engine (4-neuron parallel) ─────────────────────────────────
mlp_engine #(
    .FC1_REQ_SHIFT (`MLP_REQ_SHIFT_FC1),
    .FC2_REQ_SHIFT (`MLP_REQ_SHIFT_FC2)
) u_engine (
    .clk             (s_axi_aclk),
    .rst_n           (s_axi_aresetn),

    .start           (start_w),
    .done            (done_w),
    .result          (result_w),

    .param_addr      (param_bram_addr),
    .param_en        (param_bram_en),
    .param0_rdata    (param_bram0_rdata),
    .param1_rdata    (param_bram1_rdata),
    .param2_rdata    (param_bram2_rdata),
    .param3_rdata    (param_bram3_rdata),

    .input_addr      (input_bram_addr),
    .input_en        (input_bram_en),
    .input_rdata     (input_bram_rdata)
);

endmodule
