// mlp_params.vh is auto-generated by train_and_export.py and defines:
//   `MLP_REQ_SHIFT_FC1  - right-shift for FC1 output requantization
//   `MLP_REQ_SHIFT_FC2  - right-shift for FC2 output requantization
// Re-run train_and_export.py after retraining; then re-synthesise in Vivado.
`include "mlp_params.vh"

// =============================================================================
// mlp_engine.v
//
// Parallel-word MLP inference engine - Zybo Z7-10
// Network : 784 -> FC1(64, ReLU) -> FC2(32, ReLU) -> FC3(10, argmax)
// Weights : INT8, packed 4-per-32-bit word in the Param BRAM
// Biases  : INT32, one value per 32-bit word in the Param BRAM
// Inputs  : INT8 pixels, packed 4-per-32-bit word in the Input BRAM
// MAC     : 3 cycles per 4 multiplies (ADDR -> LATCH -> ACC)
//           One 32-bit BRAM fetch feeds four signed multiplies in parallel.
// Output  : 4-bit predicted class (0-9), one-cycle done pulse
//
// Timing at 100 MHz:
//   FC1: 64 x (6 + 196x3) ~= 38 016 cycles
//   FC2: 32 x (6 +  16x3) ~=  1 728 cycles
//   FC3: 10 x (6 +   8x3) ~=    300 cycles
//   Total ~= 40 044 cycles ~= 0.40 ms / inference
// =============================================================================
`timescale 1ns / 1ps

module mlp_engine #(
    parameter [4:0] FC1_REQ_SHIFT = `MLP_REQ_SHIFT_FC1,
    parameter [4:0] FC2_REQ_SHIFT = `MLP_REQ_SHIFT_FC2
) (
    input  wire        clk,
    input  wire        rst_n,

    input  wire        start,
    output reg         done,
    output reg  [3:0]  result,

    output reg  [15:0] param_addr,
    output reg         param_en,
    input  wire [31:0] param_rdata,

    output reg  [9:0]  input_addr,
    output reg         input_en,
    input  wire [31:0] input_rdata
);

localparam [15:0] FC1_W_BASE = 16'h0000;
localparam [15:0] FC1_B_BASE = 16'hC400;
localparam [15:0] FC2_W_BASE = 16'hC500;
localparam [15:0] FC2_B_BASE = 16'hCD00;
localparam [15:0] FC3_W_BASE = 16'hCD80;
localparam [15:0] FC3_B_BASE = 16'hCEC0;

localparam [3:0]
    S_IDLE        = 4'd0,
    S_FC_INIT     = 4'd1,
    S_BIAS_ADDR   = 4'd2,
    S_BIAS_LATCH  = 4'd3,
    S_BIAS_LOAD   = 4'd4,
    S_W_ADDR      = 4'd5,
    S_W_LATCH     = 4'd6,  // pipeline wait: BRAM samples address this cycle
    S_W_READ      = 4'd13, // latch: BRAM output valid now
    S_W_ACC       = 4'd7,
    S_SAVE        = 4'd8,
    S_NEXT_LAYER  = 4'd9,
    S_ARGMAX_INIT = 4'd10,
    S_ARGMAX_CMP  = 4'd11,
    S_DONE        = 4'd12;

reg [3:0] state;

reg [1:0]  layer;
reg [15:0] w_base;
reg [15:0] b_base;
reg [9:0]  n_in;
reg [6:0]  n_out;
reg        do_relu;

reg [6:0]  j;
reg [9:0]  i;
reg [15:0] w_row_base;
reg [15:0] b_row_base;

reg signed [31:0] acc;
reg signed [7:0]  w_latch0;
reg signed [7:0]  w_latch1;
reg signed [7:0]  w_latch2;
reg signed [7:0]  w_latch3;
reg signed [8:0]  x_latch0;
reg signed [8:0]  x_latch1;
reg signed [8:0]  x_latch2;
reg signed [8:0]  x_latch3;

reg [7:0] act1 [0:63];
reg [7:0] act2 [0:31];
reg signed [31:0] logits [0:9];

reg [3:0] argmax_k;

(* use_dsp = "yes" *) wire signed [16:0] mul0 = $signed(w_latch0) * $signed(x_latch0);
(* use_dsp = "yes" *) wire signed [16:0] mul1 = $signed(w_latch1) * $signed(x_latch1);
(* use_dsp = "yes" *) wire signed [16:0] mul2 = $signed(w_latch2) * $signed(x_latch2);
(* use_dsp = "yes" *) wire signed [16:0] mul3 = $signed(w_latch3) * $signed(x_latch3);
wire signed [19:0] mac4_sum = mul0 + mul1 + mul2 + mul3;

function [7:0] relu_clip;
    input signed [31:0] x;
    begin
        if (x <= 32'sd0)
            relu_clip = 8'h00;
        else if (x > 32'sd127)
            relu_clip = 8'h7F;
        else
            relu_clip = x[7:0];
    end
endfunction

always @(posedge clk or negedge rst_n) begin : fsm
    integer ridx;

    if (!rst_n) begin
        state      <= S_IDLE;
        done       <= 1'b0;
        result     <= 4'd0;
        param_en   <= 1'b0;
        input_en   <= 1'b0;
        param_addr <= 16'h0000;
        input_addr <= 10'h000;
        acc        <= 32'sd0;
        w_latch0   <= 8'sd0;
        w_latch1   <= 8'sd0;
        w_latch2   <= 8'sd0;
        w_latch3   <= 8'sd0;
        x_latch0   <= 9'sd0;
        x_latch1   <= 9'sd0;
        x_latch2   <= 9'sd0;
        x_latch3   <= 9'sd0;
        j          <= 7'd0;
        i          <= 10'd0;
        layer      <= 2'd0;
        w_base     <= 16'h0000;
        b_base     <= 16'h0000;
        n_in       <= 10'd0;
        n_out      <= 7'd0;
        do_relu    <= 1'b0;
        w_row_base <= 16'h0000;
        b_row_base <= 16'h0000;
        argmax_k   <= 4'd0;
        for (ridx = 0; ridx < 10; ridx = ridx + 1)
            logits[ridx] <= 32'sd0;
    end else begin
        param_en <= 1'b0;
        input_en <= 1'b0;
        done     <= 1'b0;

        case (state)
            S_IDLE: begin
                if (start) begin
                    layer <= 2'd0;
                    state <= S_FC_INIT;
                end
            end

            S_FC_INIT: begin
                j <= 7'd0;
                case (layer)
                    2'd0: begin
                        w_base     <= FC1_W_BASE;
                        b_base     <= FC1_B_BASE;
                        n_in       <= 10'd784;
                        n_out      <= 7'd64;
                        do_relu    <= 1'b1;
                        w_row_base <= FC1_W_BASE;
                        b_row_base <= FC1_B_BASE;
                    end
                    2'd1: begin
                        w_base     <= FC2_W_BASE;
                        b_base     <= FC2_B_BASE;
                        n_in       <= 10'd64;
                        n_out      <= 7'd32;
                        do_relu    <= 1'b1;
                        w_row_base <= FC2_W_BASE;
                        b_row_base <= FC2_B_BASE;
                    end
                    default: begin
                        w_base     <= FC3_W_BASE;
                        b_base     <= FC3_B_BASE;
                        n_in       <= 10'd32;
                        n_out      <= 7'd10;
                        do_relu    <= 1'b0;
                        w_row_base <= FC3_W_BASE;
                        b_row_base <= FC3_B_BASE;
                    end
                endcase
                state <= S_BIAS_ADDR;
            end

            S_BIAS_ADDR: begin
                param_addr <= b_row_base;
                param_en   <= 1'b1;
                state      <= S_BIAS_LATCH;
            end

            S_BIAS_LATCH: begin
                state <= S_BIAS_LOAD;
            end

            S_BIAS_LOAD: begin
                acc   <= $signed(param_rdata);
                i     <= 10'd0;
                state <= S_W_ADDR;
            end

            S_W_ADDR: begin
                param_addr <= w_row_base + i;
                param_en   <= 1'b1;
                if (layer == 2'd0) begin
                    input_addr <= i;
                    input_en   <= 1'b1;
                end
                state <= S_W_LATCH;
            end

            S_W_LATCH: begin
                // Pipeline wait: the Xilinx block RAM sampled the address
                // this cycle (ENB=1 was set in S_W_ADDR). DOUTB will be
                // valid on the NEXT posedge (S_W_READ). Do not read yet.
                state <= S_W_READ;
            end

            S_W_READ: begin
                // BRAM output is now valid (one full cycle after sampling).
                w_latch0 <= $signed(param_rdata[7:0]);
                w_latch1 <= $signed(param_rdata[15:8]);
                w_latch2 <= $signed(param_rdata[23:16]);
                w_latch3 <= $signed(param_rdata[31:24]);

                case (layer)
                    2'd0: begin
                        x_latch0 <= {input_rdata[7],  input_rdata[7:0]};
                        x_latch1 <= {input_rdata[15], input_rdata[15:8]};
                        x_latch2 <= {input_rdata[23], input_rdata[23:16]};
                        x_latch3 <= {input_rdata[31], input_rdata[31:24]};
                    end
                    2'd1: begin
                        x_latch0 <= {1'b0, act1[i + 10'd0]};
                        x_latch1 <= {1'b0, act1[i + 10'd1]};
                        x_latch2 <= {1'b0, act1[i + 10'd2]};
                        x_latch3 <= {1'b0, act1[i + 10'd3]};
                    end
                    default: begin
                        x_latch0 <= {1'b0, act2[i + 10'd0]};
                        x_latch1 <= {1'b0, act2[i + 10'd1]};
                        x_latch2 <= {1'b0, act2[i + 10'd2]};
                        x_latch3 <= {1'b0, act2[i + 10'd3]};
                    end
                endcase
                state <= S_W_ACC;
            end

            S_W_ACC: begin
                acc <= acc + $signed(mac4_sum);
                i   <= i + 10'd4;
                if (i == n_in - 10'd4)
                    state <= S_SAVE;
                else
                    state <= S_W_ADDR;
            end

            S_SAVE: begin
                if (do_relu) begin
                    case (layer)
                        2'd0:    act1[j] <= relu_clip($signed(acc) >>> FC1_REQ_SHIFT);
                        2'd1:    act2[j] <= relu_clip($signed(acc) >>> FC2_REQ_SHIFT);
                        default: ;
                    endcase
                end else begin
                    logits[j] <= acc;
                end

                j          <= j + 7'd1;
                w_row_base <= w_row_base + n_in;
                b_row_base <= b_row_base + 16'd4;

                if (j == n_out - 7'd1)
                    state <= S_NEXT_LAYER;
                else
                    state <= S_BIAS_ADDR;
            end

            S_NEXT_LAYER: begin
                if (layer == 2'd2) begin
                    state <= S_ARGMAX_INIT;
                end else begin
                    layer <= layer + 2'd1;
                    state <= S_FC_INIT;
                end
            end

            S_ARGMAX_INIT: begin
                result   <= 4'd0;
                argmax_k <= 4'd1;
                state    <= S_ARGMAX_CMP;
            end

            S_ARGMAX_CMP: begin
                if ($signed(logits[argmax_k]) > $signed(logits[result]))
                    result <= argmax_k;
                argmax_k <= argmax_k + 4'd1;
                if (argmax_k == 4'd9)
                    state <= S_DONE;
            end

            S_DONE: begin
                done  <= 1'b1;
                state <= S_IDLE;
            end

            default: state <= S_IDLE;
        endcase
    end
end

endmodule
